name: Tests

on: push

jobs:
  runTests:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    strategy:
      matrix:
        node-version: [18, 19, 20]
    steps:
      - uses: actions/checkout@v3
        with:
          persist-credentials: false
      
      - uses: actions/setup-node@v3
        with:
          node-version: ${{matrix.node-version}}
      
      - name: Install
        run: |
          yarn workspaces focus --production
        
      - name: Run tests
        run: |
          yarn test
